IF
	Global("BHPelltarSpawn","MYAREA",0)
	InMyArea(Player1)
	GlobalGT("Chapter","GLOBAL",%tutu_chapter_2%)
	GlobalLT("Chapter","GLOBAL",%tutu_chapter_6%)
THEN
	RESPONSE #100
		SetGlobal("BHPelltarSpawn","MYAREA",1)
		CreateCreature("BHPell",[328.367],15)
END

IF
	OR(2)
		Global("BHQuestAccept","GLOBAL",8)
		GlobalGT("Chapter","GLOBAL",%tutu_chapter_5%)
	Exists("BHPell")
THEN
	RESPONSE #100
		ActionOverride("BHPell",DestroySelf())
		SetGlobal("BHQuestAccept","GLOBAL",9)
END